pythia_160m_reward_config:
  output_dir: "./pythia-160m-reward-model"
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  num_train_epochs: 1
  learning_rate: 0.00001
  logging_steps: 10
  save_strategy: "epoch"
  bf16: true
  remove_unused_columns: false

dpo_pythia_160m_config:
  output_dir: "./pythia-160m-deduped-DPO"
  eval_strategy: "steps"
  eval_steps: 20
  per_device_eval_batch_size: 8
  save_strategy: "steps"
  save_steps: 20
  save_total_limit: null
  num_train_epochs: 3
  per_device_train_batch_size: 4
  learning_rate: 0.000005
  beta: 0.1
  logging_steps: 5
  logging_strategy: "steps"
  report_to:
    - "wandb"
  run_name: "dpo_beta0.1_bias20_run1"
  bf16: true
  gradient_checkpointing: true
  seed: 42
  load_best_model_at_end: false

ppo_pythia_160m_config:
  output_dir: "./pythia-160m-deduped-PPO"
  eval_strategy: "steps"
  eval_steps: 20
  per_device_eval_batch_size: 8
  save_strategy: "steps"
  save_steps: 20
  save_total_limit: null
  num_train_epochs: 3
  per_device_train_batch_size: 4
  learning_rate: 0.000005
  kl_coef: 0.1
  logging_steps: 5
  logging_strategy: "steps"
  report_to:
    - "wandb"
  run_name: "ppo_beta0.1_bias20_run1"
  bf16: true
  gradient_checkpointing: true
  seed: 42
  load_best_model_at_end: false
